"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional

@dataclass(slots=True, kw_only=True)
class Connection:
    node: Optional[str]
    network_name_or_chain_id: Optional[str]
    ...


@dataclass(slots=True, kw_only=True)
class ArgsRequest:
    method: str
    params: Optional[str]
    connection: Optional[Connection]
    ...


