"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from web3 import Web3
from eth_account.signers.local import LocalAccount
from typing import Optional, Union
from cbrzn_ethereum_provider_py.networks import KnownNetwork

EthereumProvider = str | Web3.HTTPProvider
@dataclass(slots=True, kw_only=True)
class ConnectionConfig:
    provider: EthereumProvider
    signer: Optional[LocalAccount]
    ...


class Connection:
    provider: Web3.HTTPProvider
    signer: Optional[LocalAccount]
    def __init__(self, config: ConnectionConfig) -> None:
        ...
    
    def set_provider(self, provider: EthereumProvider): # -> None:
        ...
    
    def set_signer(self, signer: LocalAccount): # -> None:
        ...
    
    def get_provider(self) -> Web3.HTTPProvider:
        ...
    
    def get_signer(self) -> LocalAccount:
        ...
    
    @staticmethod
    def from_node(node: str): # -> Connection:
        ...
    
    @staticmethod
    def from_network(network: Union[KnownNetwork, int]): # -> Connection:
        ...
    


