"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from cbrzn_ethereum_provider_py.connection import Connection
from cbrzn_ethereum_provider_py.wrap.types import Connection as SchemaConnection

class Connections:
    connections: Dict[str, Connection]
    default_network: str
    def __init__(self, networks: Dict[str, Connection], default_network: Optional[str]) -> None:
        ...
    
    def get(self, network: Optional[str]) -> Optional[Connection]:
        ...
    
    def set(self, network: str, connection: Connection): # -> None:
        ...
    
    def set_default_network(self, network: str, connection: Optional[Connection] = ...): # -> None:
        ...
    
    def get_default_network(self) -> str:
        ...
    
    def get_connection(self, connection: Optional[SchemaConnection]) -> Connection:
        ...
    


